src/objects/Certification_and_CEU__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Certifications and CEU's</relationshipLabel>
        <relationshipName>Certifications_and_CEU_s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FON_Awarded_Date__c</fullName>
        <label>Awarded Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FON_Contact_Hours__c</fullName>
        <label>Contact Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FON_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>OrderApi__Item__c</referenceTo>
        <relationshipLabel>Certifications and CEU's</relationshipLabel>
        <relationshipName>Certifications_and_CEU_s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FON_Number_of_Credits__c</fullName>
        <label>Number of Credits</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Certification and CEU</label>
    <nameField>
        <label>Certification and CEU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications and CEU's</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MyCertificatesCtrl.cls
public without sharing class MyCertificatesCtrl {

    @AuraEnabled
    public static List<Certification_and_CEU__c > getMyCEUs() {
        List<Certification_and_CEU__c> ceus;
        try {
            user u = [select id,contactid from user where id = : userinfo.getuserid()];
            System.debug('user'+u);
            if(u !=null){
                ceus = [SELECT Id,name, Contact__c, FON_Contact_Hours__c, FON_Item__r.name,FON_Awarded_Date__c ,FON_Number_of_Credits__c, Status__c FROM Certification_and_CEU__c where Contact__c =:u.contactid order by FON_Awarded_Date__c DESC];
                System.debug('ceus'+ceus );
            }
        }
        catch (Exception e) {
            throw new AuraHandledException(e.getMessage()+e.getStackTraceString());
        }
          return ceus;   
    }

}